run:
  timeout: 5m
  tests: false

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow
  errcheck:
    exclude-functions:
      - (net/http.ResponseWriter).Write
      - fmt.Print
      - fmt.Printf
      - fmt.Println
      - fmt.Fprintf
      - fmt.Fprintln
      - os.Remove
