[tools]
go = "1.15"

[tasks."fmt"]
depends = ["fmt:*"]

[tasks."fmt:go"]
run = "gofmt -s -w ."

[tasks."lint"]
depends = ["lint:*"]

[tasks."lint:go"]
run = "go vet ./..."

[tasks."test"]
depends = ["test:*"]

[tasks."test:go"]
run = "go test ./..."
